### PR TITLE
PORTALS-2600: rebranding as NF Research Tools Central

### PR DESCRIPTION
**Pull request by jay-hodgson**
A-New-Day-For-Ivy-Coach-300x203

### CODE REVIEW

**Review by cconrad8 — COMMENTED** [review]
@jay-hodgson @allaway after reading this I think I would like  it better if it said "The NF Research Tools Central" a few places.

If "NF Research Tools Central" is a proper noun, it seems like we should add The before. 

Thoughts?

**Comment by jay-hodgson** [comment]
@cconrad8 
> @jay-hodgson @allaway after reading this I think I would like it better if it said "The NF Research Tools Central" a few places.
> 
> If "NF Research Tools Central" is a proper noun, it seems like we should add The before.
> 
> Thoughts?
I'll edit it to be whatever you and Robert would like, just let me know (line by line) if you'd like to prefix with a "The".

**Comment by allaway** [comment]
Hmm, I can't quite put my finger on it but adding "The" to the beginning doesn't sound quite right. For example, the train station is called Grand Central, not The Grand Central. But again...I can't quite put my finger on why this doesn't sound right to me. 

(or, it sounds kind of like the difference between calling I-5 "5" or "the 5" - or for the DC area, "495" vs "the 495". Both are correct, but I think people have strong preferences for one or the other...I know I-5 vs the 5 is quite contentious here 😆

**Comment by cconrad8** [comment]
😂 it’s funny cuz I was using “Dog” as the noun replacement. So I was like
“The dog” sounds right!

It can definitely go either way. Maybe we can do a larger poll lol. I can
make one in slack?

**Comment by allaway** [comment]
Yes, that sounds great @cconrad8 !

**Review by cconrad8 — APPROVED** [review]
dropping the the!

**Review by cconrad8 — APPROVED** [review]
All is good!

**Pull request merged**
